### PR TITLE
Small improvements of the script comments

### PR DESCRIPTION
**Pull request by janmiderback**

### CODE REVIEW

**Comment by janmiderback** [comment]
Some might be pretty obvious. Just wanted all scripts to have a small description so that it is obvious what the script shows.

**Review by hrigner — APPROVED** [review]
LGTM!

**Review by StefanEnberg — APPROVED** [review]
LGTM

**Comment by janmiderback** [comment]
@StefanEnberg Looking at `formating-functions.qvs`, it says #Date in doc, but code shows Date#.
Should we update?

**Pull request merged**
